language: go
  
git:
    quiet: true

os: linux
dist: bionic

jobs:
  include:
    - stage: "Test"
      name: "Tests (Linux Ubuntu 18.04, Go 1.16.x)"
      go: 1.16.x
      script: ./test.sh
    - name: "Tests (Linux Ubuntu 18.04, Go 1.15.x)"
      go: 1.15.x
      script: ./test.sh
    - name: "Tests (Linux Ubuntu 18.04, Go 1.14.x)"
      go: 1.14.x
      script: ./test.sh

    - name: "Tests (Windows, Go 1.16.x)"
      go: 1.16.x
      script: ./test.sh
      os: windows
    - name: "Tests (Windows, Go 1.15.x)"
      go: 1.15.x
      script: ./test.sh
      os: windows
    - name: "Tests (Windows, Go 1.14.x)"
      go: 1.14.x
      script: ./test.sh
      os: windows

    - name: "Tests (OS X, Go 1.16.x)"
      go: 1.16.x
      script: ./test.sh
      os: osx
    - name: "Tests (OS X, Go 1.15.x)"
      go: 1.15.x
      script: ./test.sh
      os: osx
    - name: "Tests (OS X, Go 1.14.x)"
      go: 1.14.x
      script: ./test.sh
      os: osx

    - stage: "Deploy"
      name: "Deploy to GitHub Releases"
      go: 1.16.x
      script: ./deploy.sh
      deploy:
        provider: releases
        token: $GITHUB_TOKEN
        file:
          - "LevelDBDumper"
          - "LevelDBDumper.app.zip"
          - "LevelDBDumper.exe"
          - "LevelDBDumper_x86.exe"
        draft: true
        name: "LevelDB Dumper $TRAVIS_TAG"
        on:
          tags: true

before_install:
  - chmod +x ./test.sh
  - chmod +x ./deploy.sh
  - export GO111MODULE=auto
  - go get github.com/syndtr/goleveldb/leveldb