language: go
  
git:
    quiet: true

jobs:
  include:
    - stage: "Test"
      name: "Tests (Linux Ubuntu 18.04, Go 1.16.x)"
      go: 1.16.x
      script: ./test.sh
      os: linux
      dist: bionic
    - stage: "Test"
      name: "Tests (Linux Ubuntu 18.04, Go 1.15.x)"
      go: 1.15.x
      script: ./test.sh
      os: linux
      dist: bionic
    - stage: "Test"
      name: "Tests (Linux Ubuntu 18.04, Go 1.14.x)"
      go: 1.14.x
      script: ./test.sh
      os: linux
      dist: bionic

    - stage: "Test"
      name: "Tests (Windows, Go 1.16.x)"
      go: 1.16.x
      script: ./test.sh
      os: windows
    - stage: "Test"
      name: "Tests (Windows, Go 1.15.x)"
      go: 1.15.x
      script: ./test.sh
      os: windows
    - stage: "Test"
      name: "Tests (Windows, Go 1.14.x)"
      go: 1.14.x
      script: ./test.sh
      os: windows

    - stage: "Test"
      name: "Tests (OS X, Go 1.16.x)"
      go: 1.16.x
      script: ./test.sh
      os: osx
    - stage: "Test"
      name: "Tests (OS X, Go 1.15.x)"
      go: 1.15.x
      script: ./test.sh
      os: osx
    - stage: "Test"
      name: "Tests (OS X, Go 1.14.x)"
      go: 1.14.x
      script: ./test.sh
      os: osx

    - stage: "Deploy"
      name: "Deploy to GitHub Releases"
      go: 1.16.x
      script:
      - cd src/LevelDBDumper
      - export GOOS="linux"
      - go build -o LevelDBDumper
      - export GOOS="darwin"
      - go build -o LevelDBDumper.app
      - export GOOS="windows"
      - go build -o LevelDBDumper.exe
      - export GOARCH="386"
      - go build -o LevelDBDumper_x86.exe
      - zip -q LevelDBDumper.app.zip LevelDBDumper.app
      deploy:
        provider: releases
        token: $GITHUB_TOKEN
        file:
          - "LevelDBDumper"
          - "LevelDBDumper.app.zip"
          - "LevelDBDumper.exe"
          - "LevelDBDumper_x86.exe"
        draft: true
        name: "LevelDB Dumper $TRAVIS_TAG"
        on:
          tags: true

before_install:
  - export GO111MODULE=auto
  - go get github.com/syndtr/goleveldb/leveldb