language: go
  
git:
    quiet: true

go:
 - 1.16.X
 - 1.15.X
 - 1.14.x

jobs:
  include:
    - stage: "Test"
      name: "Tests (Linux Ubuntu 18.04)"
      script: ./test.sh
      os: linux
      dist: bionic
    - stage: "Test"
      name: "Tests (Windows)"
      script: ./test.sh
      os: windows
    - stage: "Test"
      name: "Tests (OS X)"
      script: ./test.sh
      os: osx

    - stage: "Deploy"
      name: "Deploy to GitHub"
      go: 1.16.x
      script:
      - cd src/LevelDBDumper
      - export GOOS="linux"
      - go build -o LevelDBDumper
      - export GOOS="darwin"
      - go build -o LevelDBDumper.app
      - export GOOS="windows"
      - go build -o LevelDBDumper.exe
      - export GOARCH="386"
      - go build -o LevelDBDumper_x86.exe
      - zip -q LevelDBDumper.app.zip LevelDBDumper.app
      deploy:
        provider: releases
        token: $GITHUB_TOKEN
        file:
          - "LevelDBDumper"
          - "LevelDBDumper.app.zip"
          - "LevelDBDumper.exe"
          - "LevelDBDumper_x86.exe"
        draft: true
        name: "LevelDB Dumper $TRAVIS_TAG"
        on:
          go: 1.16.x
          os: linux
          tags: true

before_install:
  - go get github.com/syndtr/goleveldb/leveldb