language: go

os:
  - linux

go:
  - 1.15.x
  - 1.14.x
  - 1.13.x
  
git:
    quiet: true

deploy:
  provider: releases
  token: $GITHUB_TOKEN
  file:
    - "LevelDBDumper"
    - "LevelDBDumper.app.zip"
    - "LevelDBDumper.exe"
    - "LevelDBDumper_x86.exe"
  draft: true
  name: "LevelDB Dumper $TRAVIS_TAG"
  on:
    tags: true

before_install:
  - sudo apt install zip -f -y
  - go get github.com/syndtr/goleveldb/leveldb

script:
  - cd src/LevelDBDumper
  - go test
  - export GOOS="linux"
  - go build -o LevelDBDumper
  - export GOOS="darwin"
  - go build -o LevelDBDumper.app
  - export GOOS="windows"
  - go build -o LevelDBDumper.exe
  - export GOARCH="386"
  - go build -o LevelDBDumper_x86.exe
  - zip -q LevelDBDumper.app.zip LevelDBDumper.app